/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.GiamGiaBUS;
import DTO.GiamGia;
import com.mysql.cj.protocol.Message;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khanh
 */
public class KhuyenMaiGUI extends javax.swing.JPanel {
    
    /**
     * Creates new form KhuyenMaiJPanel
     */
    public KhuyenMaiGUI() {
        initComponents();
        try {
            loadTableData(jtbKhuyenMai, (List<GiamGia>) GiamGiaBUS.getInstance().getAllGiamGia());
        } catch (SQLException ex) {
            Logger.getLogger(KhuyenMaiGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpnKhuyenMai = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaKhuyenMai = new javax.swing.JTextField();
        txtChuongTrinh = new javax.swing.JTextField();
        txtPhanTram = new javax.swing.JTextField();
        txtDieukien = new javax.swing.JTextField();
        jdcNgayBatDau = new com.toedter.calendar.JDateChooser();
        jdcNgayKetThuc = new com.toedter.calendar.JDateChooser();
        jbtThem = new javax.swing.JButton();
        jbtSua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbKhuyenMai = new javax.swing.JTable();

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Quản lý khuyến mãi");

        txtMaKhuyenMai.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMaKhuyenMai.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Mã khuyến mãi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        txtMaKhuyenMai.setDragEnabled(true);
        txtMaKhuyenMai.setEnabled(false);

        txtChuongTrinh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtChuongTrinh.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tên chương trình", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        txtPhanTram.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPhanTram.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Phần trăm giảm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        txtDieukien.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDieukien.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Điều kiện ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jdcNgayBatDau.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ngày bắt đầu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jdcNgayKetThuc.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ngày kết thúc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jbtThem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbtThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add_img.png"))); // NOI18N
        jbtThem.setText("Thêm");
        jbtThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThemActionPerformed(evt);
            }
        });

        jbtSua.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbtSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pencil_fix.png"))); // NOI18N
        jbtSua.setText("Sửa");
        jbtSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnKhuyenMaiLayout = new javax.swing.GroupLayout(jpnKhuyenMai);
        jpnKhuyenMai.setLayout(jpnKhuyenMaiLayout);
        jpnKhuyenMaiLayout.setHorizontalGroup(
            jpnKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKhuyenMaiLayout.createSequentialGroup()
                .addGroup(jpnKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnKhuyenMaiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpnKhuyenMaiLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(jpnKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdcNgayKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                            .addComponent(jdcNgayBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDieukien)
                            .addComponent(txtPhanTram)
                            .addComponent(txtChuongTrinh)
                            .addComponent(txtMaKhuyenMai))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jpnKhuyenMaiLayout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jbtThem, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtSua, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jpnKhuyenMaiLayout.setVerticalGroup(
            jpnKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKhuyenMaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhanTram, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDieukien, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdcNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtbKhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khuyến mãi", "Tên chương trình", "Phần trăm giảm", "Điều kiện", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbKhuyenMai);
        if (jtbKhuyenMai.getColumnModel().getColumnCount() > 0) {
            jtbKhuyenMai.getColumnModel().getColumn(0).setResizable(false);
            jtbKhuyenMai.getColumnModel().getColumn(0).setPreferredWidth(25);
            jtbKhuyenMai.getColumnModel().getColumn(1).setResizable(false);
            jtbKhuyenMai.getColumnModel().getColumn(2).setResizable(false);
            jtbKhuyenMai.getColumnModel().getColumn(3).setResizable(false);
            jtbKhuyenMai.getColumnModel().getColumn(4).setResizable(false);
            jtbKhuyenMai.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpnKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThemActionPerformed
        // TODO add your handling code here:
       try {
        // Create a GiamGia object
        GiamGia giamGia = new GiamGia();

        // Validate GiamGia data (optional, assuming a validate() method exists)
        // giamGia.validate(); // Uncomment this line if you have a validate() method

        // Set GiamGia properties from GUI elements
        giamGia.setTenGiamGia(txtChuongTrinh.getText());
        giamGia.setPhanTramGiam(Integer.parseInt(txtPhanTram.getText()));
        giamGia.setDieuKien(Float.parseFloat(txtDieukien.getText()));
        giamGia.setNgayDB(jdcNgayBatDau.getDate());
        giamGia.setNgayKT(jdcNgayKetThuc.getDate()); // Assuming end date comes from jdcNgayKetThuc

        // Add the discount using GiamGiaBUS
        GiamGiaBUS.getInstance().addGiamGia(giamGia);

           loadTableData(jtbKhuyenMai, (List<GiamGia>) GiamGiaBUS.getInstance().getAllGiamGia());
        // Display success message (optional)
        JOptionPane.showMessageDialog(null, "Giảm giá đã được thêm thành công!");
            
        } catch (Exception e) {
        // Handle parsing errors (e.g., invalid input for percentage or condition)
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
       
    }//GEN-LAST:event_jbtThemActionPerformed

    private void jbtSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSuaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jbtSuaActionPerformed
    public void loadTableData(JTable table, List<GiamGia> data) {
        // Create a KhuyenMaiTableModel (replace with your actual model class name)
   
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Mã KM");
        tableModel.addColumn("Chương trình");
        tableModel.addColumn("Phần trăm KM");
        tableModel.addColumn("Điều kiện");
        tableModel.addColumn("Ngày bắt đầu");
        tableModel.addColumn("Ngày kết thúc");
        tableModel.addColumn("Tình trạng");
        for (GiamGia giamGia : data) {
        tableModel.addRow(new Object[]{
            giamGia.getMaGiam(), // Assuming 'maGiam' is a property in your GiamGia class
            giamGia.getTenGiamGia(), // Assuming 'tenGiamGia' is a property in your GiamGia class
            giamGia.getPhanTramGiam() + "%",
            giamGia.getDieuKien(),
            giamGia.getNgayDB().toString(), // Format date as needed
            giamGia.getNgayKT().toString(), // Format date as needed
            // Add data for "Tình trạng" column (replace with your logic)
            "Chưa Áp Dụng" // Or any default status
        });}
        // Set the table model for the JTable
        table.setModel(tableModel);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtSua;
    private javax.swing.JButton jbtThem;
    private com.toedter.calendar.JDateChooser jdcNgayBatDau;
    private com.toedter.calendar.JDateChooser jdcNgayKetThuc;
    private javax.swing.JPanel jpnKhuyenMai;
    private javax.swing.JTable jtbKhuyenMai;
    private javax.swing.JTextField txtChuongTrinh;
    private javax.swing.JTextField txtDieukien;
    private javax.swing.JTextField txtMaKhuyenMai;
    private javax.swing.JTextField txtPhanTram;
    // End of variables declaration//GEN-END:variables
}


